= Cross-Testing Feedback

__Durchführende Gruppe: 39__

__Anwendung von Gruppe: Unterbrunner Ärztehaus__

== Getestetes System
Dem großen Unterbrunner Ärztehaus wird eine Apotheke angegliedert.
Es handelt sich um einen Verkaufsraum mit drei Kassen und einer Selbstbedienungsabteilung für nicht rezeptpflichtige Waren (Pflaster,
medizinische Badezusätze, Heiltees aller Art, Pflegesalben etc.).
Daneben gibt es ein kleines chemisches Labor, wo auf Anforderung der Ärzte spezielle Pulver, Salben und Tinkturen bereitet werden können
(abzuholen einen Tag nach Bestellung). Bei Bestellungen von Mixturen oder nicht vorrätigen Medikamenten werden den Kunden Bestellzettel
mit einer eindeutigen Identifikationsnummer ausgegeben (das Rezept verbleibt in der Apotheke).
Die Apothekenschränke sind wie üblich alphabetisch sortiert. An jeder Medikamentenpackung ist ein Strichcode angebracht, welcher das Medikament und die Packungsgröße eindeutig identifiziert.
Bei Verkauf eines Medikaments wird der Code an der Kasse eingelesen. Auf diese Weise wird der Posten auf die Kundenrechnung und
gleichzeitig in die tägliche Nachbestellung übernommen. Medikamente werden entweder wie andere Waren bar bezahlt oder an Kassenpatienten gegen Entrichtung der Zuzahlung (10% des Preises,
jedoch mindestens 5 EUR und maximal 10 EUR pro Arzneimittel) abgegeben.
Kassenleistungen werden von den Apotheken mit einer Zentralkasse monatlich abgerechnet. Mit Hilfe der neuen Apotheke ersparen sich die Praxen auch die Bewirtschaftung eigener Medizinvorräte:
Neben den Mitarbeitern der Apotheke haben auch die Ärzte und einige besonders zuverlässige Arzthelferinnen jederzeit Zugang zum Medikamentenschrank. Für diesen Zweck gibt es eine Tür zur Apotheke, die vom Ärztehaus aus durch Eingabe einer praxisspezifischen PIN
geöffnet werden kann. Auf der anderen Seite der Tür befindet sich ein Lesegerät, an dem beim Verlassen der Strichcode der entnommenen Medikamente erfaßt wird.
Zwecks eindeutiger Zuordnung der Medikamente und um den Betrieb der Apotheke nicht übermäßig zu stören, hat zu einem Zeitpunkt höchstens
eine Praxis Zugang zur Apotheke. Die Ärzte haben erklärt, daß dies keine wesentliche Einschränkung darstellt. Die Abrechnung mit den
einzelnen Arztpraxen erfolgt monatlich. Alle Lesegeräte sind an den Computer der Apotheke angeschlossen, über den die automatische
Nachbestellung von Medikamenten, die eigene Bilanz und die Abrechnung mit den Ersatzkassen läuft.
Außerdem wird an diesem Computer wöchentlich eine Liste der Medikamente ausgedruckt, deren Verfallsdatum in der nächsten Woche erreicht
wird oder das schon überschritten ist. Diese werden wöchentlich ausgesondert.
Die Einführung eines weiteren Dienstes - die Auslieferung von Medikamenten an das nahegelegene Altersheim und andere
bewegungseingeschränkte Patienten - wird derzeit diskutiert. Entwickeln Sie eine Software, die die oben dargestellten Vorgänge (einschließlich
Personalverwaltung) geeignet unterstützt. Vorschläge zur Gestaltung des Auslieferservice werden ebenfalls erwartet.

== Fehler-Report
// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Pfad |Parameter |Beschreibung |Rückgabe
| /pwChange | "ADMIN"; 1234, 123456, 123456 | Altes Passwort falsch | Passwort geändert
| /katalog | "ADMIN" | Kann nicht zum Warenkorb hinzufügen | …
| /inventory | "ADMIN" | Medikament, Preis Filter | Error 
| /inventory | "ADMIN" | Neues Medikament | Error 
| /users/update/email/admin | "ADMIN"; "tom" | Keine Bean Validation => Wenn Browser den input type "email" nicht unterstützt werden fehlerhafte Einträge gespeichert | Neue Email "tom" 
| /users/update/AddressPostcode/admin | "ADMIN"; "test" | Keine Bean Validation | Error 
| /workers/update | "ADMIN"; "test" | Keine Bean Validation | Error 
| … | … | … | … 
| … | … | … | … 
| … | … | … | … 
|===

== Sonstiges

=== Fehlende Features

=== UX: Interaktion mit der Anwendung (Usability)
* Startseite lenkt von Hauptfunktion Katalog ab
* Ohne Anmeldung kann nicht in den Warenkorb gelegt werden, erschwert Kaufentscheidung
** Registrieren benötigt viele Daten welche auch später ergänzt werden könnten, da unwesentlich für Login
* Rezeptfrei/ pflichtig an unterster Stelle in Filterhierarchie, obwohl meist verwendeter Filter vor allem bei Online Apotheke
* Als Admin nicht Bestellen zu können ist sehr umständlich, trotz der höherrangigen Berechtigung wird einem Funktionalität verwehrt
* Trennung zwischen Personenbezogenen und Anwendungsbezogenen Funktionen fehlt in Navbar
** Profil, Anmelden und Passwort ändern sind getrennt
** "Profil" wird für (Öffentliche) Nutzerprofile genutzt und "Account" für private Daten zwischen Kunde und Unternehmen
** Wenn Warenkorb leer, kein Hinweis oder Aufforderung zur Weiterleitung auf Katalog

=== UI: Optik der Anwendung


== Verbesserungsvorschläge
* "Passwort aendern" -> "Passwort ändern"
