= Entwicklerdokumentation

[options="header"]
|===
| Version | Bearbeitungsdatum  
| 1.0     | 29.11.2020    
|===

== Inhaltsverzeichnis

. link:#einführung-und-ziele[Einführung und Ziele] +
.. link:#aufgabenstellung[Aufgabenstellung] +
.. link:#qualitätsziele[Qualitätsziele] +

== Einführung und Ziele

=== Aufgabenstellung

In so schwierigen Zeiten wird es immer wichtiger, dass essenzielle Dienste wie die Medikamentenversorgung so zugänglich wie möglich gestaltet werden. Deshalb soll eine neue Webapp für die Apotheke des Unterbrunner Ärztehaus entstehen, welche unter anderem die Möglichkeit der Lieferung für bewegungseingeschränkte oder gefährdete Personen ermöglicht.

Die Apotheke hat mehrere Benutzer mit verschiedenen Rechten. Jeder Besucher kann das Inventar einsehen, ohne sich anzumelden, um bequem den Bestand prüfen zu können. Im Inventar wird unterschieden zwischen Medikamenten und Zutaten für das Labor. Außerdem hat jeder Artikel einen Bestand, eine Nachbestellmenge und eine Information, ob der Artikel rezeptpflichtig ist.

Nach einer kurzen Anmeldung können Nutzer auch Waren in die Apotheke bestellen lassen, bewegungseingeschränkte Nutzer können außerdem diese Waren zu sich nach Hause liefern lassen. Arzt Praxen bekommen ihren eigenen Account, welcher es einer Praxis ermöglicht auf den Medikamentenschrank zuzugreifen. In der Apotheke selbst gibt es die Möglichkeit Kassenaccounts zu erstellen, um in Zukunft mehrere Selbstbedienerkassen zu unterstützen. Mitarbeiter können neben dem abrechnen von rezeptpflichtigen Medikamenten auch eigene hinzufügen, welche im Labor hergestellt wurden. Zudem können Mitarbeiter sich Urlaub nehmen. Der Boss hat die Möglichkeit Artikel manuell nachzubestellen, Nutzer zu erstellen, Mitarbeiter einzustellen, zu feuern und deren Gehalt anzupassen, außerdem kann er die Finanzen der Apotheke verwalten.

Wenn eine Bestellung ausgelöst wurde, werden Zeitpunkt, Betrag, Artikel und zugehörige Menge, Kunde und eventuelle Rezept-Nummern gespeichert. Wenn der Vorgang abgeschlossen wurde, wird bei regulären Kunden abhängig von der Krankenkasse abgerechnet. Bei Praxen wird am Ende des Monats abgerechnet. Zudem werden die Gehälter der Mitarbeiter so verwaltet, genau wie die monatliche Abrechnung mit den Krankenkassen.

Wenn eine Praxis eine Anfrage an das Labor schickt, wird eine offene Bestellung erzeugt, der im Labor tätige Mitarbeiter kann diese dann erfüllen, indem er die benötigten Materialien aus dem Inventar entfernt und daraufhin die Bestellung als abgeschlossen kennzeichnet.

Auch die Inventarverwaltung soll erleichtert werden, daher wird wöchentlich eine Liste mit Medikamenten erstellt, deren Verfallsdatum in der nächsten Woche erreicht wird oder das schon überschritten ist.

Zwar können Nutzer sich frei Registrieren, mithilfe einer E-Mail-Adresse und eines Passworts, allerdings muss die Akkreditierung der Bewegungseinschränkung vor Ort geschehen. Das Erstellen von Kassen, Praxen und Mitarbeiter Accounts wurde erleichtert, damit nicht jeder erst einen Account manuell erstellen muss.

Das Ziel der Anwendung ist es, sehr zuverlässig und langwierig betrieben werden zu können, weshalb eine Webapp eine gute Wahl darstellt. Zudem bietet die modualre Nutzer-Struktur die Möglichkeit weitere Account-Typen ohne viel Aufwand hinzuzufügen.

Der Aufbau der Seite sollte additiv sein, also niemals dem Nutzer Funktionalität entziehen, wenn seine Freigabe steigt. Das heißt, dass der Boss mindestens genau so viele Funktionen wie der Mitarbeiter hat. Dies hilft zusätzlich bei der Inbetriebnahme des Systems, da Nutzer sich gegenseitig besser unterstützen können.

Das Design soll barrierefrei und minimalistisch sein. Daher soll auf aufwendige Bilder verzichtet werden und statt dessen auf korrekte Kontrast verhätnisse und gut skalierende Schrift geachtet werden.

=== Qualitätsziele

* Quali

== Randbedingungen
* Hardware-Vorgaben
* Software-Vorgaben
* Vorgaben zum Betrieb des Software

== Kontextabgrenzung
* Kontextdiagramm

== Lösungsstrategie
=== Erfüllung der Qualitätsziele
[options="header"]
|=== 
|Qualitätsziel |Lösungsansatz
|... |...
|===

=== Softwarearchitektur
* Beschreibung der Architektur anhand der Top-Level-Architektur oder eines Client-Server-Diagramms

=== Entwurfsentscheidungen

==== Verwendete Muster

- Spring MVC

==== Persistenz



==== Benutzeroberfläche



==== Verwendung externer Frameworks

[options="header", cols="1,2"]
|===
|Externes Package |Verwendet von (Klasse der eigenen Anwendung)
|... |... 
|===

== Bausteinsicht
* Entwurfsklassendiagramme der einzelnen Packages

[options="header"]
|=== 
|Klasse/Enumeration |Description
|...|...
|===

=== Rückverfolgbarkeit zwischen Analyse- und Entwurfsmodell
_Die folgende Tabelle zeigt die Rückverfolgbarkeit zwischen Entwurfs- und Analysemodell. Falls eine Klasse aus einem externen Framework im Entwurfsmodell eine Klasse des Analysemodells ersetzt,
wird die Art der Verwendung dieser externen Klasse in der Spalte *Art der Verwendung* mithilfe der folgenden Begriffe definiert:_

* Inheritance/Interface-Implementation
* Class Attribute
* Method Parameter

[options="header"]
|===
|Klasse/Enumeration (Analysemodell) |Klasse/Enumeration (Entwurfsmodell) |Art der Verwendung
|...|...|...
|===

== Laufzeitsicht
* Darstellung der Komponenteninteraktion anhand eines Sequenzdiagramms, welches die relevantesten Interaktionen darstellt.

== Technische Schulden
* Auflistung der nicht erreichten Quality Gates und der zugehörigen SonarQube Issues zum Zeitpunkt der Abgabe

