= Zeiterfassung für Gruppe 39

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Clemens |Falk |Jonas |Lars |Lukas |Timon |Meeting
|1  |420 |200 |360 |550 |300 |540 |240    
|2  |540 |600 |480 |700 |660 |660 |210    
|3  |210 |300 |540 |250 |150 |300 |300    
|4  |190 |120 |500 |400 |405 |360 |200    
|5  |900 |400 |520 |…   |520 |400 |90   
|6  |95   |300   |120 |…   |80   |110 |35   
|7  |900   |840   |1020  |…   |960   |1200 |60     
|8  |…   |960   |1300   |…   |1100   |1500  |100  
|9  |…   |…   |…   |…   |…   |120   |200  
|10 |…   |…   |…   |…   |…   |1320 |120   
|11 |…   |…   |…   |…   |…   |…   |…   
|12 |…   |…   |…   |…   |…   |…   |…     
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
