== Funktionale Anforderungen
In diesem Abschnitt werden die funktionellen Anforderungen des Systems aufgelistet. Die Tabelle enthält:

* Eine eindeutige Kennung der Anforderung (ID), die während des gesamten Projekts zur Referenzierung verwendet werden kann
* die aktuelle Version der Anforderung, da Änderungen an einer Anforderung während des gesamten Projekts erfolgen können
* Eine kurze Bezeichnung der Anforderung
* Die Beschreibung der Anforderung

Anmerkung: Eine funktionale Anforderung definiert eine Funktion des Systems, die zur Erfüllung der Kundenbedürfnisse implementiert werden soll (z.B. wie durch Anwendungsfälle gezeigt). Im Idealfall enthält sie einen Satz von Eingaben für die betreffende Funktionalität, das beabsichtigte Verhalten und das Ergebnis davon.

Anmerkung: Die funktionalen Anforderungen werden verwendet, um darzustellen, was genau implementiert werden muss (aus Sicht des Entwicklers). Da die Anwendungsfälle meist relativ nahe an der Domäne liegen und meist nicht-technisch sind (können sogar von einem nicht-technischen Kunden geschrieben werden), ist es notwendig, die vom Kunden bereitgestellten Informationen zu spezifizieren und zu organisieren.


[options="header", cols="2h, 1, 3, 12"]
|===
|ID
|Version
|Name
|Description

|01
|v0.1
|Authentisieren
a|
Benutzer werden in Gruppen unterteilt, zum Beispiel: Online Kunden, Mitarbeiter, Ärzte von verschieden Praxen. Benutzer werden durch folgende Attribute Authentifiziert: 

*	Benutzername
*	Passwort

|02
|v0.1
|Registrierung
a|
Online Kunden können sich jederzeit registrieren mit:

*	E-Mail 
*	Benutzername
*	Adresse
*	Passwort

Jeder Nutzer hat einen eindeutigen Benutzernamen, d.h. Benutzernamen können nicht zweimal vergeben werden.

Mitarbeiter werden vom Chef bzw. Administrator erstellt, gelöscht und editiert. Mit folgenden Attributen:

*	Arbeitszeiten
*	Name
*	Anschrift
*	Gehalt
|03
|v0.1
|Registrierung Validieren
a|
Es wird überprüft ob:

*	Die E-Mail den Richtlinien entspricht
*	Der Benutzer ist mit den gegebenen expliziten Daten noch nicht in der Datenbank


|04
|v0.1
|Inventur
a|
Alle Arzneimittel werden beim Eingang registriert und in einen Lagerbestand eingetragen.
Wenn eines Verkauft wird, wird dies ebenfalls registriert

|05
|v0.1
|Nachbestellung
a|
Das System erkennt, wenn ein Produkt nicht mehr im Lager vorhanden ist und bestellt automatisch nach.

|06
|v0.1
|Ablaufdatumsverarbeitung
a|
Wenn ein Medikament ein Monat vor dem Ablaufdatum ist, werden die Mitarbeiter benachrichtigt und aufgefordert diese Zeitnah zu entsorgen.

|07
|v0.1
|Katalog
a|
Das System stellt ein Lesezugriff auf die Medikamenten-Datenbank für Online-Kunden zur Verfügung.  Mitarbeiter, Ärzte und der Chef haben entsprechend einen Änderungszugriff.

|08
|v0.1
|Kasse
a|
Eine integrierte Kasse Verwaltet Bestellungen, Gehaltsauszahlungen und Verkäufe, Miete und Strom, allgemeine Einnahmen und Ausgaben, sowie Abrechnung mit den jeweiligen Praxen. Desweiteren können Rechnungen und Berichte erstellt und archiviert werden

|09
|v0.1
|Produktdetails
a|
Produkte sollten folgende Attribute haben:

*	ID
*	Name
*	Verpackungsgröße
*	Ablaufdatum
*	Bezeichnung
*	Beschreibung
*	Preis
*	Rezeptpflichtig Ja/Nein

|10
|v0.1
|Warenkorb
a|
Online registrierte und authentifizierte Nutzer haben die Möglichkeit Produkte in einen Warenkorb zu legen und diese zu bestellen. Ein nicht eingeloggter Benutzer bekommt eine Nachricht sich anzumelden bzw. sich zu registrieren.

|11
|v0.1
|Warenkorb einsehen
a|
Im Warenkorb wird die Vollständige Produktbezeichnung, Preis und evtl. Bild angezeigt. Ebenso werden der Gesamtpreis und die Lieferadresse zur manuellen Validierung angezeigt. (nur für angemeldete Benutzer)

|12
|v0.1
|Bezahlung
a|
Nachdem man den Warenkorb eingesehen hat wird man zu Bezahlung weitergeleitet.


|13
|v0.1
|Administrator Konto
a|
Das Konto wird beim Initialisieren des Systems festgelegt. Die Möglichkeiten sind:

*	Mitarbeiter hinzufügen/entfernen
*	Gehälter festlegen
*	Manuelle Bestellung
*	Einsicht aller registrierten Benutzer
*	Bearbeitung der registrierten Benutzer
*	Übersicht vom Lagerbestand
*	Übersicht aller Bestellungen und Verkäufe

|14
|v0.1
|Kunden Konto
a|
Das Konto wird beim Initialisieren des Systems festgelegt. Die Möglichkeiten sind:

*	Manuelle Bestellung
*	Information zu Verfügbarkeit gelisteter Medikamente
*	Übersicht der bestellten Artikel
*   Kunden können Account selbst löschen
*   Haben einen Warenkorb

|15
|v0.1
|Mitarbeiter Konto
a|
Das Konto wird beim Initialisieren des Systems festgelegt. Die Möglichkeiten sind:

*	Manuelle Bestellung
*	Information zu Verfügbarkeit aller Medikamente
*	Übersicht der aller Kunden
*   Mitarbeiter können ihren account nicht löschen
*   Können Bargeld entgegen nehmen und das Medikament somit bezahlen
*   Können nicht verfügbare Medikamente reservieren
|===
