= Pflichtenheft
:project_name: Projektname
== __{project_name}__

[options="header"]
|===
| Version | Bearbeitungsdatum
| 0.1     | 08.11.2020    
| 0.5     | 15.11.2020    
|===

== Inhaltsverzeichnis
==== link:#zusammenfassung[Zusammenfassung] +
==== link:#aufgabenstellung-und-zielsetzung[Aufgabenstellung und Zielsetzung] +
==== link:#interessensgruppen[Interessensgruppen] +
==== link:#systemgrenze-und-top-level-architektur[Systemgrenze und Top-Level-Architektur] +
======= link:#kontextdiagramm[Kontextdiagramm] +
======= link:#top-level-architektur[Top-Level-Architektur] +

== Zusammenfassung
Das Pflichtenheft bietet einen Überblick zu Zielsetzung und Umsetzung des Softwareprojekts.

== Aufgabenstellung und Zielsetzung
Es soll eine Website für die Apotheke des Unterbrunner Ärztehaus entstehen. In der Apotheke gibt es eine Selbstbedienungsabteilung für nicht rezeptpflichtige Waren in der Kunden Artikel einscannen und bezahlen können sollen. Zusätzlich gibt es ein chemisches Labor, wo auf Anforderung von Praxen spezielle Pulver, Salben und Tinkturen bereitet werden sollen (abzuholen einen Tag nach Bestellung). Bei Bestellungen von Mixturen oder nicht vorrätigen Medikamenten werden den Kunden Bestellzettel mit einer eindeutigen Identifikationsnummer ausgegeben. An jeder Medikamentenpackung ist ein Strichcode angebracht, welcher das Medikament und die Packungsgröße eindeutig identifiziert. Bei Verkauf eines Medikaments wird der Code an der Kasse eingelesen. Auf diese Weise wird der Posten auf die Kundenrechnung und gleichzeitig in die tägliche Nachbestellung übernommen. Medikamente werden entweder wie andere Waren bar bezahlt oder an Kassenpatienten gegen Entrichtung der Zuzahlung (10% des Preises, jedoch mindestens 5 EUR und maximal 10 EUR pro Arzneimittel) abgegeben. Kassenleistungen werden von den Apotheken mit einer Zentralkasse monatlich abgerechnet. Mit Hilfe der neuen Apotheke ersparen sich die Praxen auch die Bewirtschaftung eigener Medizinvorräte: Neben den Mitarbeitern der Apotheke haben auch Praxen Zugang zum Medikamentenschrank. Für diesen Zweck gibt es eine Tür zur Apotheke, die vom Ärztehaus aus durch Eingabe einer praxisspezifischen PIN geöffnet werden kann. Auf der anderen Seite der Tür befindet sich ein Lesegerät, an dem beim Verlassen der Strichcode der entnommenen Medikamente erfaßt wird. Zwecks eindeutiger Zuordnung der Medikamente und um den Betrieb der Apotheke nicht übermäßig zu stören, hat zu einem Zeitpunkt höchstens eine Praxis Zugang zur Apotheke. Die Abrechnung mit den einzelnen Arztpraxen erfolgt monatlich. Alle Lesegeräte sind an den Computer der Apotheke angeschlossen, über den die automatische Nachbestellung von Medikamenten, die eigene Bilanz und die Abrechnung mit den Ersatzkassen läuft. Außerdem wird an diesem Computer wöchentlich eine Liste der Medikamente ausgedruckt, deren Verfallsdatum in der nächsten Woche erreicht wird oder das schon überschritten ist. Diese werden wöchentlich ausgesondert. Außerdem soll ein Dienst zum auslieferun von Medikamenten entwickelt werden.

== Produktnutzung
Das System soll für eine Apotheke genutzt werden um ihre Produkte zu verkaufen. Die Software soll auf einem Server laufen und ist über das Internet (via Browser) zu erreichen.
Das System soll erreichbar und visuell optimiert sein für folgende Browser:
Mozilla Firefox, Version 55.0.3+
Google Chrome, Version 61.0.3163+
Die Hauptnutzer des Programms sind die Mitarbeiter der Apotheke, welche typische Webseitennavigation beherrschen, wie auch Ärzte und ihre vertrauenswürdigen Schwestern, der Chef, Selbstbedienungskundschaft und registrierte Kunden bei sich daheim.

== Interessensgruppen
[options="header"]
|===
| Name | Priorität (1..5) | Beschreibung | Ziele
| Ärztehaus | 5 | Auftraggeber | Automatisierter Verkauf von Medikamenten, Gemeinsames Lager von Apotheke und Praxen, Mehr Geld verdienen
| Kunden | 4 | Primärer Nutzer | Medikamente kaufen / geliefert bekommen, Gutes User Experience
| Administratoren | 2 | Verwaltung des Computersystems | Möglichkeit, sämtliche Daten im System zu Überprüfen, Prozesse Überwachen und evtl. verändern
| Programmierer | 3 | Wir |Entwicklung und Instandhaltung der Software, Gut erweiterbare Software, Geringer Instandhaltungsaufwand, Gute Debugging-Möglichkeiten
| Ärzte / Praxen | 3 | An das Ärztehaus angrenzende Praxen | Zugriff auf Lager
|===

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

include::Anwendungsfaelle.adoc[]

== Funktionale Anforderungen

=== Muss-Kriterien
- Verwaltung aller in der Apotheke befindlichen Medikamente
- Automatisches tägliches nachbestellen, wenn ein Vorrat aufgebraucht ist
- Kassenverwaltung (Einnahmen, Ausgaben, Gehälter)
- Es hat jeweils eine Praxis Zugang zu den Medikamenten
- Monatliche Abrechnung mit Arztpraxen
- Verfallsdatum berücksichtigen und Mitarbeiter benachrichtigen
- Auslieferservice für Orte der gleichen Postleitzahl

=== Kann-Kriterien
- Kalendermanagement für Arbeitszeiten und Urlaubstage der Mitarbeiter
- Hinzufügen und entfernen von Mitarbeitern
- Intelligentes Nachbestellen bzw. reservieren von Medikamenten

== Nicht-Funktionale Anforderungen

=== Qualitätsziele

1 = Not Important ..
5 = Very Important
[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Quality Demand           | 1 | 2 | 3 | 4 | 5
|Maintainability          |   |   |   | x |
|Usability                |   |   | x |   |
|Security                 |   | x |   |   |
|===

=== Konkrete Nicht-Funktionale Anforderungen

:desired-uptime: 99,5%

== UI Prototyp

include::ui.adoc[]

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?
