= Protokoll Gruppe 39

Treffen am 02.11.2020

Ort:      Zoom +
Beginn:   09:20 Uhr +
Ende:     10:40 Uhr

__Schriftführer: Timon Trettin__

*Nächstes Treffen* +
10.11.2020, 16:40 Uhr, Zoom

*Teilnehmer* +
- Lennart Wittkowski: Tutor, Kunde +
- Lars +
- Falk Natkowski +
- Lukas L. +
- Jonas +
- Timon Trettin +
- Clemens +

*UML Tool: MagicDraw*

*Apotheke*
- Kundengespräch: Details im Pflichtenheft

== Aufgaben bis zum 08.11.2020 23:59

*Pflichtenheft Apotheke*

*Videothek* +
- Clemens: Nachbestellung (Chef kann Nachbestellen im Lager, Warnen bei Niedrigem Bestand) +
- Lars: Warenkorb (Anzahl Artiekl ändern, löschen, Nicht über bestand bestellen) +
- Jonas: Durchschnitt berechnen (Aus Bewertungen Durchschnitt errechnen und darstellen) +
- Lukas: Registrierung neuer Nutzer (Passwort richtlinien (Timon), keine Doppelten Namen in der Datenbank) +
- Falk: Suche (Schlagwortsuche, keine leeren Strings oder leerzeichen, min. 2 Zeichen) +
- Timon: Möglichkeit zum ändern des Passwortes (Passwort ändern, Altes + Neues + Bestätigung Neues, Mindestlänge, Großbuchstaben, Zahlen, Sonderzeichen)
